TwitchGuide/TwitchGuide/Controllers/ProfileController.cs
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.Owin;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;
using TwitchGuide.DAL;
using TwitchGuide.Models;

namespace TwitchGuide.Controllers
{
    public class ProfileController : Controller
    {
        private TwitchContext db = new TwitchContext();

        // Index
        public ActionResult Search(string name = null)
        {
            var profileModel = new ProfileModel { };
            string username = "";
            ViewBag.edit = "False";

            if (name == null) //load current user's profile if logged in
            {

                if (User.Identity.IsAuthenticated)
                {
                    username = User.Identity.GetUserName();
                    ViewBag.edit = "True";
                }
                else
                {
                    return RedirectToAction("Index", "Home");
                }

                var sched1 = db.Users.Where(p => p.Username == username).FirstOrDefault().Schedules.ToList();
                var tb1 = sched1.Join(db.Timeblocks,
                         p => p.TimeblockID,
                         e => e.Index,
                         (p, e) => new Timeblock
                         {
                             Index = e.Index,
                             StartHour = e.StartHour,
                             StartMinute = e.StartMinute,
                             EndHour = e.EndHour,
                             EndMinute = e.EndMinute,
                             Day = e.Day
                         }).ToList();

                profileModel = new ProfileModel
                {
                    TimeblockObj = tb1,
                    UserObj = db.Users.Where(p => p.Username == username).FirstOrDefault()
                };
                ViewBag.token = profileModel.UserObj.AuthToken;
                return View(profileModel);
            }


            var findUser = db.Users.Where(p => p.Username == name).FirstOrDefault();

            if (findUser == null)
            {
                return HttpNotFound();
            }

            var tb = findUser.Schedules.ToList().Join(db.Timeblocks,
                          p => p.TimeblockID,
                          e => e.Index,
                          (p, e) => new Timeblock
                          {
                              Index = e.Index,
                              StartHour = e.StartHour,
                              StartMinute = e.StartMinute,
                              EndHour = e.EndHour,
                              EndMinute = e.EndMinute,
                              Day = e.Day
                          }).ToList();


            profileModel = new ProfileModel
            {
                TimeblockObj = tb,
                UserObj = db.Users.FirstOrDefault()
            };
            ViewBag.token = profileModel.UserObj.AuthToken;
            return View(profileModel);
        }


        //
        //CRUD Functionality Below
        //

        // GET: Profile/Create
        [Authorize]
        public ActionResult Create()
        {
            return base.View();
        }

        // POST: Profile/Create
        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "StartHour,StartMinute,EndHour,EndMinute,Day,Index")] Timeblock timeblock)
        {

            if (ModelState.IsValid)
            {
                if (timeblock.StartHour > 12 || timeblock.EndHour > 12)
                {
                    ViewBag.message = "Start Hour and End Hour must be between 1 and 12";
                    return View(timeblock);
                }

                //Adjust times to reflect AM/PM toggle
                if (Request["AM_Start"] != "on" && timeblock.StartHour != 12)
                {
                    timeblock.StartHour += 12;
                }
                if (Request["AM_End"] != "on" && timeblock.EndHour != 12)
                {
                    timeblock.EndHour += 12;
                }

                //make sure the start time is before the end time
                if (timeblock.StartHour > timeblock.EndHour)
                {
                    ViewBag.message = "The End Time cannot be before the Start Time.";
                    return View(timeblock);
                }
                if (timeblock.StartHour == timeblock.EndHour)
                {
                    if (timeblock.StartMinute >= timeblock.EndMinute)
                    {
                        ViewBag.message = "The End Time cannot be before the Start Time.";
                        return View(timeblock);
                    }
                    if ((timeblock.EndMinute - timeblock.StartMinute) < 15)
                    {
                        ViewBag.message = "The timeblock duration cannot be less than 15 minutes.";
                        return View(timeblock);
                    }
                }

                //Max timeblock length is 10 hours
                if ((timeblock.EndHour - timeblock.StartHour) > 9)
                {
                    ViewBag.message = "The timeblock duration cannot be greater than 9 hours";
                    return View(timeblock);
                }

                    //Check if timeblock already exists in DB
                    var check = db.Timeblocks.Where(p =>
                    (p.Day == timeblock.Day) &&
                    (p.StartHour == timeblock.StartHour) &&
                    (p.StartMinute == timeblock.StartMinute) &&
                    (p.EndHour == timeblock.EndHour) &&
                    (p.EndMinute == timeblock.EndMinute)).FirstOrDefault();

                if (check == null) //Timeblock doesn't exist yet
                {
                    db.Timeblocks.Add(timeblock);
                    db.SaveChanges();

                    var username = User.Identity.GetUserName();
                    var currentUser = db.Users.Where(p => p.Username == username).FirstOrDefault();

                    db.Schedules.Add(new Schedule { UserID = currentUser.UserID, TimeblockID = timeblock.Index });
                    db.SaveChanges();
                    return RedirectToAction("Search");
                }
                else
                {
                    var username = User.Identity.GetUserName();
                    var currentUser = db.Users.Where(p => p.Username == username).FirstOrDefault();

                    //check if the user already has that timeblock
                    var check2 = db.Schedules.Where(p => (p.UserID == currentUser.UserID) && (p.TimeblockID == check.Index)).FirstOrDefault();

                    if (check2 == null) //User does not have the timeblock
                    {
                        db.Schedules.Add(new Schedule { UserID = currentUser.UserID, TimeblockID = check.Index });
                        db.SaveChanges();
                        return RedirectToAction("Search");
                    }
                }
            }
            return View(timeblock);
        }


        // GET: Timeblocks/Delete/#
        [Authorize]
        public ActionResult Delete(byte? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Timeblock timeblock = db.Timeblocks.Where(p => p.Index == id).FirstOrDefault();
            if (timeblock == null)
            {
                return HttpNotFound();
            }

            var username = User.Identity.GetUserName();
            var currentUser = db.Users.Where(p => p.Username == username).FirstOrDefault();

            Schedule mapping = currentUser.Schedules.Where(p => p.TimeblockID == id).FirstOrDefault();
            db.Schedules.Remove(mapping);
            db.SaveChanges();
            return RedirectToAction("Search");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

TwitchGuide/TwitchGuide/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8" />
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title>@ViewBag.Title - Twitch Channel Guide</title>
	@Styles.Render("~/Content/css")
	@Scripts.Render("~/bundles/modernizr")
	@Scripts.Render("~/bundles/themeScript")
	@RenderSection("styles", required: false)

</head>
<body>
    <header class="header black-bg">
        <div class="sidebar-toggle-box">
            <div class="fa fa-bars tooltips" data-placement="right" data-original-title="Toggle Navigation"></div>
        </div>
        <!--logo start-->
        <a href="@Url.Action("Index", "Home")" class="logo"><b>Twitch Guide</b></a>
        <!--logo end-->
        <div class="nav notify-row" id="top_menu">
            <!-- links start -->
            <ul class="nav top-menu">
                <li>
                    <a href="@Url.Action("AllUsers", "Home")" class="menuLinks" data-icon="&#xe007;">  Members</a>
                </li>
                <li>
                    <button type="button" class="btn btn-theme" data-toggle="dropdown" id="toggleSearch">Looking For Someone?</button>
                </li>
                <li>
                    <span class="nav navbar-nav form-inline" id="SearchBar">
                        <input type="text" class="form-control" name="name" id="name" placeholder="Search by Username">
                        <button class="btn btn-theme" id="btnSearch">Search</button>
                    </span>
                </li>
            </ul>
            <!-- links end -->

        </div>
        <div class="top-menu">
            <ul class="nav pull-right top-menu">
                <li>@Html.Partial("_LoginPartial")</li>
            </ul>
        </div>
    </header>
    <!--top menu end-->
    <!--sidebar start-->
    <aside>
        <div id="sidebar" class="nav-collapse ">
            <!-- sidebar menu start-->
            <ul class="sidebar-menu" id="nav-accordion">
                <p class="centered"><a href="@Url.Action("Search", "Profile", new { name = "" })"><img src="~/Content/TylerAvatar.png" class="img-circle" width="60"></a></p>
                <h5 class="centered">TConnorsBitsmith</h5>

            </ul>
            <!-- sidebar menu end-->
        </div>
    </aside>
    <!--sidebar end-->
    <section id="main-content">
        <section class="wrapper">
            @RenderBody()
        </section>
    </section>
    
            <!--footer start-->
            <footer class="myFooter">
                    <a href="@Url.Action("AboutUs", "Home")" class="AboutUsLink"><b>About Us</b></a>
            </footer>
            <!--footer end-->


            @Scripts.Render("~/bundles/jquery")
            @Scripts.Render("~/bundles/bootstrap")
            @RenderSection("scripts", required: false)

            <script>
                $(document).ready(function () {
                    $("#SearchBar").hide();
                });
            </script>
            <script>
                $(document).ready(function () {
                    $("#toggleSearch").click(function () {
                        $("#SearchBar").toggle(1000);
                    });
                });
            </script>
            <script>
                $("#btnSearch").click(function () {
                    location.href = "../Users/" + $("#name").val();
                });
            </script>
            @if (Request.IsAuthenticated)
            {
                <script>
                    //Gets the Logo.png for the current user, and displays it next to the name
                    $(document).ready(function () {
                        $.ajax({
                            url: 'https://api.twitch.tv/kraken/user',
                            type: 'GET',
                            dataType: 'json',
                            success: function (result) {
                                $("#LogoSpot").html("<img src='" + result.logo + "' height=32 width=32></img>");
                            },
                            beforeSend: setAuthHeader
                        });
                    });
                    $(document).ready(function () {
                        $.ajax({
                            url: 'https://api.twitch.tv/kraken/user',
                            type: 'GET',
                            dataType: 'json',
                            success: function (result) {
                                $("#UserNameDisplay").html("<a href='/Manage'>" + result.name + "</a>");
                            },
                            beforeSend: setAuthHeader
                        });
                    });
                    function setAuthHeader(xhr) {
                        var token = "@ViewBag.token";
                        xhr.setRequestHeader('Accept', 'application/vnd.twitchtv.v5+json');
                        xhr.setRequestHeader('Client-ID', 'kx6k6d64t0ok27s5sfyo1w5n1q3dn6');
                        xhr.setRequestHeader('Authorization', 'OAuth ' + token);
                    };
                </script>
            }
</body>

</html>